server:
  port: 8080

spring:
  datasource:
    url: "jdbc:sqlserver://ISW-230522-1310\\SQLEXPRESS;encrypt=false;integratedSecurity=true;databaseName=payroll"
    driver-class-name: "com.microsoft.sqlserver.jdbc.SQLServerDriver"
  jpa:
    properties:
      hibernate:
        dialect: "org.hibernate.dialect.SQLServerDialect"
    hibernate:
      ddl-auto: "create"


